fwouts/previewjs

- integrations/intellij/src/main/kotlin/com/previewjs/intellij/plugin/services/PreviewJsService.kt
This should hopefully help with #53 and #140.
> fix: add support for fish shell

- app/client/src/design/Link/Link.tsx
Thank you @slorber for the tip!
https://twitter.com/sebastienlorber/status/1512420374201446405
> refactor: use ComponentProps type for simplicity

- frameworks/react/src/analyze-component.spec.ts
- frameworks/react/src/analyze-component.ts
> fix(react): automatically convert required properties with a default value to optional

- iframe/preview/index.html
This should address https://github.com/fwouts/previewjs/issues/714.
> feat: add default padding on body

- app/tests/react/storybook.spec.ts
- app/tests/solid/storybook.spec.ts
- app/tests/vue2/storybook.spec.ts
- app/tests/vue3/storybook.spec.ts
- frameworks/react/preview/index.tsx
- frameworks/solid/preview/index.tsx
- frameworks/vue2/preview/index.ts
- frameworks/vue3/preview/index.ts
This should address https://github.com/fwouts/previewjs/issues/715.
> feat: support default args in Storybook stories

- iframe/preview/index.html
See discussion in https://github.com/fwouts/previewjs/issues/714.
> fix: use padding instead of margin on iframe body

- .github/workflows/release-csf3.yaml
- app/tests/react/storybook.spec.ts
- app/tests/solid/storybook.spec.ts
- app/tests/vue2/storybook.spec.ts
- app/tests/vue3/storybook.spec.ts
- csf3/LICENSE
- csf3/build.config.ts
- csf3/package.json
- csf3/src/extract-csf3-stories.spec.ts
- csf3/src/extract-csf3-stories.ts
- csf3/src/index.ts
- csf3/tsconfig.json
- frameworks/react/package.json
- frameworks/react/preview/index.tsx
- frameworks/react/src/extract-component.spec.ts
- frameworks/react/src/extract-component.ts
- frameworks/solid/package.json
- frameworks/solid/preview/index.tsx
- frameworks/solid/src/extract-component.spec.ts
- frameworks/solid/src/extract-component.ts
- frameworks/vue2/package.json
- frameworks/vue2/preview/index.ts
- frameworks/vue2/src/extract-component.ts
- frameworks/vue3/package.json
- frameworks/vue3/preview/index.ts
- frameworks/vue3/src/extract-component.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- scripts/release.ts
> feat: add support for Component Story Format 3.0

- loader/src/checkNodeVersion.ts
- loader/src/checkNpmVersion.ts
- loader/src/installer.ts
> fix: crash with a helpful error message when Node 12 or earlier is detected

- loader/package.json
- loader/runner.d.ts
- loader/src/installer.ts
- pnpm-lock.yaml
> fix: prevent two processes from simultaneously installing dependencies

- integrations/vscode/src/index.ts
- integrations/vscode/src/start-server.ts
- pnpm-lock.yaml
- server/package.json
- server/src/client.ts
- server/src/index.ts
> feat(vscode): automatically use Node from WSL if not available in Windows environment

- integrations/intellij/controller/esbuild.js
- integrations/intellij/controller/src/config.ts
- integrations/intellij/controller/src/main.ts
- integrations/intellij/src/main/kotlin/com/previewjs/intellij/plugin/services/PreviewJsService.kt
- integrations/vscode/src/start-server.ts
> feat(intellij): automatically use Node from WSL if not available in Windows environment 

- serializable-values/src/generate-serializable-value.spec.ts
- serializable-values/src/generate-serializable-value.ts
- type-analyzer/src/definitions.ts
- type-analyzer/src/dereference.ts
- type-analyzer/src/generate-type-declarations.spec.ts
- type-analyzer/src/generate-type-declarations.ts
- type-analyzer/src/is-valid.ts
- type-analyzer/src/strip-unused-types.ts
- type-analyzer/src/type-parameters.ts
> fix: add explicit support for tuple types

- app/tests/react/error-handling.spec.ts
- app/tests/solid/error-handling.spec.ts
- app/tests/vue2/console.spec.ts
- app/tests/vue2/error-handling.spec.ts
- app/tests/vue3/console.spec.ts
- app/tests/vue3/error-handling.spec.ts
- e2e-test-runner/src/helpers/app-controller.ts
Note: this PR will make some tests fail. This is expected, fixes will follow (no new release until then).
> test: ensure that tested components are always detected

- app-foundations/src/state/PreviewState.ts
- app-foundations/src/window.ts
This will ultimately be deprecated as you'll instead be able to view associated stories for a component.
> refactor: remove "v" query param for variants

- vfs/src/real.ts
This prevents a bug where, when React project code imports `prop-types`, we end up mistakenly importing prop-types.ts from the React plugin instead of the intended package.
> fix(vfs): prevent mapping of virtual files outside of "from" directory

- frameworks/vue2/package.json
- frameworks/vue2/src/index.ts
- frameworks/vue2/tests/error-handling.spec.ts
- pnpm-lock.yaml
> refactor(vue2): migrate from vite-plugin-vue2 to @vitejs/plugin-vue2

- config/src/read-config.ts
- core/package.json
- core/src/previewer.ts
- core/src/vite/vite-manager.ts
- daemon/src/client.ts
- daemon/src/index.ts
- pnpm-lock.yaml
> fix: prevent persistent crash when encountering invalid preview.config.js or postcss.config.js

- core/package.json
- core/src/find-files.ts
- core/src/vite/vite-manager.ts
- pnpm-lock.yaml
> fix: remove usage of recrawl, which breaks with nested symlinks

- core/src/previewer.ts
- framework-plugins/svelte/package.json
- framework-plugins/svelte/src/index.ts
- pnpm-lock.yaml
> feat(svelte): extract aliases from svelte.config.js automatically

- integrations/intellij/gradle.properties
- integrations/intellij/src/main/kotlin/com/previewjs/intellij/plugin/actions/OpenPreviewAction.kt
- integrations/intellij/src/main/kotlin/com/previewjs/intellij/plugin/inlays/InlayProviderFactory.kt
- integrations/intellij/src/main/kotlin/com/previewjs/intellij/plugin/services/ProjectService.kt
This also fixes the issue where inlay hints were not appearing on first open.
See https://intellij-support.jetbrains.com/hc/en-us/community/posts/4968667359122-Restarting-inlay-hints-provider?page=1#community_comment_11888562167314
> fix(intellij): switch back to DocumentListener as VFS_CHANGES only occur on window blur

- integrations/intellij/build.gradle.kts
- integrations/intellij/gradle.properties
> fix(intellij): add back compatibility with all future versions
